name: Build and Push Multi-Architecture Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven with settings.xml
        run: echo $MAVEN_SETTINGS | base64 --decode > $HOME/.m2/settings.xml
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get Project Version
        id: project-version
        run: echo "PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build the project for AMD64
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: ./mvnw -B -Dpackaging=docker package jib:dockerBuild@build-amd64 --file pom.xml

      - name: Build the project for ARM64
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: ./mvnw -B -Dpackaging=docker package jib:dockerBuild@build-arm64 --file pom.xml

      - name: Create and push multi-architecture manifest
        run: |
          docker buildx create --name mybuilder || true
          docker buildx use mybuilder
          docker buildx inspect --bootstrap
          docker buildx imagetools create --tag docker.io/krickert/${{ github.event.repository.name }}:${{ env.PROJECT_VERSION }} \
            docker.io/krickert/${{ github.event.repository.name }}:${{ env.PROJECT_VERSION }}-amd64 \
            docker.io/krickert/${{ github.event.repository.name }}:${{ env.PROJECT_VERSION }}-arm64